[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hcb-api-sdk"
version = "1.0.5"
description = "Python SDK to interact with Hack Club Bank"
authors = [{ name = "Cody Wilson", email = "cody@codywilson.co" }]
requires-python = ">=3.8"
readme = "README.md"
license = "MIT"
dependencies = [
    "requests>=2.32.0",
]

[dependency-groups]
dev = ["black>=24.4.2,<25"]

[tool.hatch.build.targets.wheel]
packages = ["src/hcb-api"]
