# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .base import BaseModel

import contextlib
with contextlib.suppress(ImportError):
    from .transaction import Transaction
    from .organization import Organization


@JsonMap({"id_": "id"})
class Sponsor(BaseModel):
    """Sponsor

    :param id_: id_, defaults to None
    :type id_: str, optional
    :param name: name, defaults to None
    :type name: str, optional
    """

    def __init__(self, id_: str = None, name: str = None):
        if id_ is not None:
            self.id_ = id_
        if name is not None:
            self.name = name


class InvoiceStatus(Enum):
    """An enumeration representing different categories.

    :cvar OPEN: "open"
    :vartype OPEN: str
    :cvar PAID: "paid"
    :vartype PAID: str
    :cvar VOID: "void"
    :vartype VOID: str
    """

    OPEN = "open"
    PAID = "paid"
    VOID = "void"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, InvoiceStatus._member_map_.values()))


@JsonMap({"id_": "id", "date_": "date"})
class Invoice(BaseModel):
    """Invoice model

    :param id_: id_, defaults to None
    :type id_: str, optional
    :param object: object, defaults to None
    :type object: str, optional
    :param href: href, defaults to None
    :type href: str, optional
    :param memo: memo, defaults to None
    :type memo: str, optional
    :param transaction: Transaction model, defaults to None
    :type transaction: Transaction, optional
    :param organization: Organization model, defaults to None
    :type organization: Organization, optional
    :param amount_cents: amount_cents, defaults to None
    :type amount_cents: str, optional
    :param sponsor: sponsor, defaults to None
    :type sponsor: Sponsor, optional
    :param date_: date_, defaults to None
    :type date_: str, optional
    :param status: status, defaults to None
    :type status: InvoiceStatus, optional
    """

    def __init__(
        self,
        id_: str = None,
        object: str = None,
        href: str = None,
        memo: str = None,
        transaction: Transaction = None,
        organization: Organization = None,
        amount_cents: str = None,
        sponsor: Sponsor = None,
        date_: str = None,
        status: InvoiceStatus = None,
    ):
        if id_ is not None:
            self.id_ = id_
        if object is not None:
            self.object = object
        if href is not None:
            self.href = href
        if memo is not None:
            self.memo = memo
        if transaction is not None:
            self.transaction = self._define_object(transaction, Transaction)
        if organization is not None:
            self.organization = self._define_object(organization, Organization)
        if amount_cents is not None:
            self.amount_cents = amount_cents
        if sponsor is not None:
            self.sponsor = self._define_object(sponsor, Sponsor)
        if date_ is not None:
            self.date_ = date_
        if status is not None:
            self.status = self._enum_matching(status, InvoiceStatus.list(), "status")
